### ISSUE TITLE
start ui error

### ISSUE THREAD

**Issue by yunluo440825** [limpbrains/django-cc#10]
1.linux ui
ml@ubuntu:~/django-cc/testproject$ python3 manage.py runserver 0.0.0.0:8332
Performing system checks...

System check identified no issues (0 silenced).
March 30, 2019 - 08:13:27
Django version 2.1.7, using settings 'testproject.settings'
Starting development server at http://0.0.0.0:8332/
Quit the server with CONTROL-C.
Invalid HTTP_HOST header: '0.0.0.0:8332'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
Bad Request: /
[30/Mar/2019 08:13:36] "GET / HTTP/1.1" 400 65136
Invalid HTTP_HOST header: '0.0.0.0:8332'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
Bad Request: /favicon.ico
[30/Mar/2019 08:13:38] "GET /favicon.ico HTTP/1.1" 400 65118
Not Found: /
[30/Mar/2019 08:14:03] "GET / HTTP/1.1" 404 2030
Not Found: /favicon.ico
[30/Mar/2019 08:14:07] "GET /favicon.ico HTTP/1.1" 404 2081
Not Found: /
[30/Mar/2019 08:14:17] "GET / HTTP/1.1" 404 2030
Not Found: /
[30/Mar/2019 08:14:25] "GET / HTTP/1.1" 404 2030
2.
Page not found (404)
Request Method: 	GET
Request URL: 	http://localhost:8332/

Using the URLconf defined in testproject.urls, Django tried these URL patterns, in this order:

    admin/
    ^cc/

The empty path didn't match any of these.

You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.

**Comment by limpbrains** [comment]
django-cc doesn't have any wallet UI. its a library
It only has `models` and `tasks` to help you build your own service.

to use django-cc you need to create your own django project, install django-cc, add it to INSTALLED_APPS
Everything else is on you.

**Comment by yunluo440825** [comment]
thanks

**Comment by limpbrains** [comment]
I have an old project
https://github.com/limpbrains/django-cc-wallet
It is an attempt to create UI for django-cc
You can take a look at it.
It is outdated and I'm not maintaining it! But you can look at the source code, probably it will help.

Cheers

**Comment by yunluo440825** [comment]
thanks
