### ISSUE TITLE
Missing documentation?

### ISSUE THREAD

**Issue by ghost** [limpbrains/django-cc#11]
Hello,

your Project seems intressting to me but i dont know how to use it?

Can you please create a documentation where we have some examples in place. I currently dont understand how to create Wallets for my users or how to get things setup Witz the current doc.

Thanks

**Comment by limpbrains** [comment]
Hi

Sure it would be nice to have docs, but I don't have time to work on them.
To attach Wallet to User model you need some proxy like
```
from django.contrib.auth.models import User
from cc.models import Wallet

class Proxy(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    wallet = models.OneToOneField(Wallet, on_delete=models.CASCADE)
```
Or substituting a custom User model

You can find more examples in Django docs https://docs.djangoproject.com/en/2.2/topics/auth/customizing/#extending-the-existing-user-model

Also I have an old project https://github.com/limpbrains/django-cc-wallet
It is an attempt to create UI for django-cc
You can take a look at it.
It is outdated and I'm not maintaining it! But you can look at the source code, probably it will help.

Cheers
