### ISSUE TITLE
cant start celery

### ISSUE THREAD

**Issue by kambic** [limpbrains/django-cc#12]
hello.

can you please help me, i cant start celery worker. i did make  Currency model in python, but celery gives me  error:

> (venv) kamba@kubuThink:~/www/escrow$ celery worker -A tst.cel.app
> Error: 
> Unable to load celery application.
> The module tst was not found.

**Comment by limpbrains** [comment]
Hi!

django-cc it's a library. You need to create your own project and add it to it.
Here tst - it's a name of your project. Your setup will be different.

Cheers

**Comment by kambic** [comment]
i did create my own project and add library into. i got  Currency model in db. so than i need to run tasks.py with celery to get it running ?

**Comment by limpbrains** [comment]
After you created your project, you need to setup celery in it.
for example I have this celery.py config in my django project
```
from __future__ import absolute_import

import os

from celery import Celery

from django.conf import settings

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'tst.settings')

CELERY_BROKER = getattr(
    settings,
    'CELERY_BROKER',
    'redis://localhost:6379/5')

app = Celery('tst', broker=CELERY_BROKER)

app.config_from_object('django.conf:settings')
app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)

@app.task(bind=True)
def debug_task(self):
    print('Request: {0!r}'.format(self.request))
```
then
celery worker -A tst.celery.app

read celery docs for more info

**Comment by Desperado1001** [comment]
Error: 
Unable to load celery application.
The module dailyfresh was not found.

My celery configure like this:

```python
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'dailyfresh.settings')
django.setup()

from goods.models import *
from django_redis import get_redis_connection

app = Celery('celery_tasks.tasks', broker='redis://127.0.0.1:6379/0')

```
