### ISSUE TITLE
Support for shielded transactions

### ISSUE THREAD

**Issue by dahifi** [limpbrains/django-cc#14]
@limpbrains see you're still active on this project, and I was hoping to use it for a zcash fork that only uses z_ operations. 

Wanted to know if you were working on adding such functionality. I've forked it and have started trying to update things on my end, but I was wondering if you might have time to talk with me to clear up some questions I have. 

I've added a boolean to the currency model for 'shielded_transactions', and have been able to get refill_address_queue working: 

```
@shared_task()
def refill_addresses_queue():
    for currency in Currency.objects.all():
        coin = AuthServiceProxy(currency.api_url)
        count = Address.objects.filter(currency=currency, active=True, wallet=None).count()

        if count < settings.CC_ADDRESS_QUEUE:
            for i in range(count, settings.CC_ADDRESS_QUEUE):
                try:
                    if currency.shielded_transactions:
                        Address.objects.create(address=coin.z_getnewaddress(settings.CC_ACCOUNT), currency=currency)
                    else:
                        Address.objects.create(address=coin.getnewaddress(settings.CC_ACCOUNT), currency=currency)
                except (socket_error, CannotSendRequest) :
                    pass
```

Wanted to pick your brain if you're game...

**Comment by limpbrains** [comment]
Hi!

So it's a good start. I didn't try to implement this.
The next big question - does zcashd have the same API to get history of regular shielded transactions 

I suggest you to try tests. Recently I've created tests for each currency. Each tests runs cryptocurrency daemon in docker and uses testnet to get real transaction. 

To run tests simple install docker and run `docker-compose up` in django-cc dir
Zcash tests runs pretty long, because of the shielded transactions.
If these tests will pass on your branch, then it is possible to get this feature into django-cc

Zcash tests https://github.com/limpbrains/django-cc/blob/master/cc/tests/tests_zcash_regtest.py

Cheers

**Comment by dahifi** [comment]
Yea, I believe in TDD. :) 

I wish I knew enough about design patterns to be able to add a wrapper to add this functionality without modifying your app at all, I think the idiosyncrasies of this fork is going to be so different...

I'm still kinda new and learning what all the API calls do, but each z_address maintains it's own balance among the private total. 

You can't query private txs like you can do on a public blockchain. There's no explorer on this thing at all, so if the daemon doesn't catch the operation... I think. 

I'm going over the tests_mock module now. Can you tell me if the following tests are supposed to fail? It seems that the assertions should fail, IDK if there's something I'm missing here. 

```
    def test_active_address(self):
        active = Address.objects.create(address='1111111111111111111114oLvT2', wallet=self.wallet, currency=self.btc, active=True)
        Address.objects.create(address='1AGNa15ZQXAZUgFiqJ2i7Z2DPU2J6hW62i', wallet=self.wallet, currency=self.btc, active=False)
        self.assertEqual(self.wallet.get_address(), active)

    def test_unused_address(self):
        unused = Address.objects.create(address='1Eym7pyJcaambv8FG4ZoU8A4xsiL9us2zz', wallet=self.wallet, currency=self.btc, active=False)
        Address.objects.create(address='LRNYxwQsHpm2A1VhawrJQti3nUkPN7vtq3', currency=self.ltc, active=True)
        self.assertEqual(self.wallet.get_address(), unused)

```

**Comment by limpbrains** [comment]
No, they should not fail. Both are fine
