### ISSUE TITLE
celery call cc.tasks.refill_addresses_queue don't work

### ISSUE THREAD

**Issue by valentinc94** [limpbrains/django-cc#16]
when I write that command it stays as loading but absolutely nothing happens.

**Comment by limpbrains** [comment]
Hi
Probably you didn't start celery server. This command will send request to celery and it will run the task.

**Comment by valentinc94** [comment]
yep i solved thanks how i can get my address? from my wallet

**Comment by valentinc94** [comment]
celery call wallet.tas.refill_addresses_queue stay and don't load

**Comment by valentinc94** [comment]
![Captura de Pantalla 2020-03-03 a la(s) 12 48 04 p  m](https://user-images.githubusercontent.com/52929539/75803978-5188b480-5d4d-11ea-9b02-8974b9884d6c.png)

**Comment by limpbrains** [comment]
If celery server doesn't respond to celery call command, there is a problem in your celery setup, not in django-cc.
Probably you can try `celery call -b redis://localhost:6379/0 wallet.tasks....`
