### ISSUE TITLE
When adding a new currency, what should "last_block" be?

### ISSUE THREAD

**Issue by JMIdeaMaker** [limpbrains/django-cc#18]
I'm trying to add my cryptocurrency, Zeal, and it is not working (wallet.get_address() for a newly created wallet is None). I think my magicbyte and dust values are correct. I think it's the last_block that is throwing things off. Also, my api_url is my full node. Is that alright?

My coin is a Litecoin 0.8.7.5 fork.

**Comment by limpbrains** [comment]
So you need your coin daemon to be running.
Create instance of Currency model pointing to Zeal RPC
Setup celery server
Then `celery call cc.tasks.refill_addresses_queue`
This task will query coins daemon and create addresses in DB.
Then next time you call wallet.get_address() it will take address from address pool and attach to wallet model.
Cheers
