### ISSUE TITLE
Use celery as a python function, not at the command line?

### ISSUE THREAD

**Issue by unicornlox** [limpbrains/django-cc#2]
How to use the `celery worker -A tst.cel.app` and `celery call cc.tasks.refill_addresses_queue` celery commands as a python function, except for the command line?

Included in the following commands
`celery call cc.tasks.process_withdraw_transactions`
`cc.tasks.query_transactions`

```
import celery

def celery(self):
    a = celery call cc.tasks.process_withdraw_transactions
    return a
```
As an example; I would do it like this?

**Comment by limpbrains** [comment]
Take a look at the `delay` from celery docs http://docs.celeryproject.org/en/latest/userguide/calling.html
I think this is what you needed
It would be something like this:
```python
from cc.tasks import refill_addresses_queue

def celery(self):
    a = refill_addresses_queue.delay()
    return a
```
