### ISSUE TITLE
Generation of new address 

### ISSUE THREAD

**Issue by julius121** [limpbrains/django-cc#20]
Hi,
First off thanks for great library.
Quick question, after I initially import my address from my bitcoind wallet.dat file using the refill_address_queue
What happens when I require say another 100 address? Are they automatically generated or do I need to run a script to ensure that fresh address are being generated periodically by bitcoind.
Finally from what I understand btc address are a one use thing therefore each time a confirmed transaction hits the wallet i should generate a new address for the wallet and update the wallet model with the new address?
Thanks again

**Comment by limpbrains** [comment]
Hi!
You need to periodically run refill_address_queue to have a reserve of new addresses. I've designed django-cc so it could work even if bitcoind is offline for some time.

It is a good practice to use each address only once. Unfortunately django-cc doesn't mark as active=False automatically. You can do this somehow. Probably it should be a new feature of django-cc, thanks for the idea.

**Comment by julius121** [comment]
Thanks that's great, will this library work with an encrypted wallet?
Also you should consider posting your BTC wallet to the readme, if I ever use this in production I'll be sure to drop something for your time

**Comment by julius121** [comment]
Thanks thats great, will this library work with an encrypted wallet?
Also consider leaving your btc wallet in the readme.
If I ever use this in production I'd like to donate.

**Comment by julius121** [comment]
Hi, so iv set up celery beat to periodically run refill address queue however it only takes a maximum of 20 address, ie: no matter how many times I run refill address queue after the first time no new address are saved to the database, any idea what the issue could be?

**Comment by julius121** [comment]
Another quick question, when I call the withdraw_to_address or transfer methods from the wallet model I am only able to pass in whole numbers as amounts to either withdraw or transfer between wallets.
Does this mean I can only transfer whole bitcoins or am I missing something and is there a way that I can enter decimal values for the amount of btc I wish to transfer.
The error im receiving when inputting a decimal value is: "unsupported  operand type(s) for -: 'decimal.Decimal' and 'float'"
Thanks

**Comment by limpbrains** [comment]
I'm using Decimal everywhere for amounts 
Do not use float when you work with money to avoid problems with precision
```
In [2]: 0.1 + 0.2
Out[2]: 0.30000000000000004
```

**Comment by julius121** [comment]
Thanks! Apologies for my foolishness
