### ISSUE TITLE
running celery tasks as celery beat task

### ISSUE THREAD

**Issue by julius121** [limpbrains/django-cc#21]
Hi again,
Just a quick question,
I am currently running refill_address_queue
Process_withdraw_transaction and query_transaction as a celery beat task configured in settings and am calling it directly from cc.tasks is this the correct way to have it configured or should I be doing it differently?
Thanks!

**Comment by julius121** [comment]
also is there a way to get transaction history for a particular wallet, for example to see all outgoing, incoming and confirmed transactions that have occurred to that particular wallet/address.

**Comment by limpbrains** [comment]
> Hi again,
> Just a quick question,
> I am currently running refill_address_queue
> Process_withdraw_transaction and query_transaction as a celery beat task configured in settings and am calling it directly from cc.tasks is this the correct way to have it configured or should I be doing it differently?
> Thanks!

Yes, it's correct to run query_transaction and process_withdraw_transaction periodically.
Also, you can call celery task to have immediate action.
For example, user created withdraw transaction, you use `celery.app.task.Task.delay` or `celery.app.task.Task.apply_async` to run process_withdraw_transaction.
But if you want bunch transactions, to save on fees, you just run it periodically.

**Comment by limpbrains** [comment]
> also is there a way to get transaction history for a particular wallet, for example to see all outgoing, incoming and confirmed transactions that have occurred to that particular wallet/address.

`wallet.get_operations()` returns list of Operations. 

```
for o in wallet.get_operations():
    o.created
    o.balance
    o.reason.txid
    o.reason.address
```
take a look at cc/models.py Operation for all the fields you can get

**Comment by limpbrains** [comment]
I've improved README. Please take a look. If there are anything you have found unclear and it is not yet covered, please let me know.

**Comment by julius121** [comment]
Looks great! Thanks for the help
