### ISSUE TITLE
monero support

### ISSUE THREAD

**Issue by torphix** [limpbrains/django-cc#25]
hi there,
Nice project.
Have you tested with monero?
How do you derive the magic byte values for crypto (sorry couldn't find a definitive answer from google)
Thanks!

**Comment by limpbrains** [comment]
> Have you tested with monero?

No, never

>  How do you derive the magic byte values for crypto (sorry couldn't find a definitive answer from google)

It is a decimal prefix of an address 
https://en.bitcoin.it/wiki/List_of_address_prefixes

Looks like monoro has different from bitcoin base58 standard. https://monerodocs.org/cryptography/base58/
So django-cc can't validate it 

I think monero went too far from bitcoin and it may be require quite a lot of work to make it works with django-cc

**Comment by torphix** [comment]
Thanks all the best!
