### ISSUE TITLE
How to do the deposit transaction 

### ISSUE THREAD

**Issue by nakul-narayanan** [limpbrains/django-cc#3]
Hi, I'm just integrating this repo with my django app, i' m able to do the withdraw transaction. but  i don't know how to do the deposit transaction with celery . please help me out  also please put the deposit transaction example in readme @limpbrains

**Comment by limpbrains** [comment]
Hi
You need to create Wallet
```
from cc.models import Wallet

wallet = Wallet.objects.create(
    currency=currency
)

address = wallet.get_address()
```

This will give you an address to which you can send funds

**Comment by nakul-narayanan** [comment]
Hi @limpbrains , i have already created wallet using django. but i don'nt know how to do transfer. i found a celery task cc.tasks.process_deposit_transacation. but it requires some params like transaction id, how can i get the transaction id . please point ' i'm new to bitcoin :)

**Comment by limpbrains** [comment]
You need to send bitcoins to address, celery will find this new deposit transaction for you and increase the balance
You don't need to create deposit transaction by hands, it will be created automatically

**Comment by nakul-narayanan** [comment]
How to can i send the bitcoin to that address ? through django or bitcoin qt ?

**Comment by limpbrains** [comment]
bitcoin qt, or any other bitcoin wallet

**Comment by nakul-narayanan** [comment]
can i send the bitcoin using django? i can see some methods in Wallet model

**Comment by limpbrains** [comment]
Yes, you can use wallet.withdraw
But it doesn't make sense, deposit transaction should income outside of django app
Imagine you are building web wallet app for users. They can create a wallet, deposit funds using their local bitcoin wallet. And withdraw them, when needed.
