### ISSUE TITLE
What’s currency?

### ISSUE THREAD

**Issue by beeqb** [limpbrains/django-cc#7]
Hello mate.
Tell me pls, what kind of currencies do you support?
Bitcoin = BTC 
BitcoinCash = BCH or BCC
Litecoin = LTC
Dash = DASH
Dogecoin = DOGE
Is this correct? What else?
Thank you for support.

**Comment by limpbrains** [comment]
Hi
I've tested it on BTC, DOGE, DSH, LTC, ZEC
It should work fine with other coin based on bitcoin software, but no guarantees

**Comment by beeqb** [comment]
Oh, cool. So how I can connect related and additional blockchains to the Django-cc?

**Comment by limpbrains** [comment]
Download bitcoind, install it, edit bitcoin.conf, enable server mode, add rpc login and password. Make sure it's working
Create django app, install django-cc. In django admin add Currency. In conncecion string fill in 
http://rpclogin:rcppassword@localhost:8332/

After that you should be able to create cc.models.Wallet instance and send-recieve funds.

Also you need to run celery to periodically ask for new transactions from bitcond

Same for any other cryptocurrencies

**Comment by beeqb** [comment]
About Bitcoin NO QUESTIONS. Questions are for LTC, for example.
Thank you.

**Comment by limpbrains** [comment]
No difference for BTC or LTC
