### ISSUE TITLE
should Wallet model methods be atomic? 

### ISSUE THREAD

**Issue by markblundeberg** [limpbrains/django-cc#8]
Hi, I'm interested in using this codebase for a project. One thing I was wondering about is why, for example, `Wallet.withdraw_to_address` doesn't wrap everything in a transaction. It seems there could be various race conditions between the time when the model is first fetched from database, and when .save() is called.

I am a bit new to django as well, though, is there some reason why locking would not be necessary?

**Comment by limpbrains** [comment]
Hi, you are right, every balance update should be done in transaction.
In my code I have a higher level wrapper with `@transaction.atomic` and to get wallets I'm always using select for update, like `Wallet.objects.select_for_update().get(addresses=address)` to get a lock over the Wallet. 

I'm not sure is it correct to wrap model methods and how nested `@transaction.atomic` will work in this case.

Probably balance updates could be rewritten using the F expression https://docs.djangoproject.com/en/dev/ref/models/expressions/#f-expressions

I'm not an expert in Django/SQL

**Comment by markblundeberg** [comment]
Yes, I was looking into it more and I think that's the right approach -- make sure the caller uses transaction.atomic *and* select_for_update to create the Wallet instance.

It is important that the transaction is already started and the row is locked by the time that the model instance object is created, since that makes sure when you do balance = balance + 1, the old balance is correctly up-to-date.

The model methods are therefore correct. Thanks! :+1:

**Comment by yunluo440825** [comment]
docker-compose Start, how can DNS report errors
