### ISSUE TITLE
docker-compose start

### ISSUE THREAD

**Issue by yunluo440825** [limpbrains/django-cc#9]
docker-compose Start, how can DNS report errors

**Comment by yunluo440825** [comment]
How does the docker-compose UI start

**Comment by limpbrains** [comment]
Hi. I do not have an example of docker-compose for django-cc
I'm using docker / docker-compose to run tests. 
Dockerfile https://github.com/limpbrains/django-cc/blob/master/Dockerfile
docker-compose https://github.com/limpbrains/django-cc/blob/master/docker-compose.yml

 You can build something based on them. I hope it helps 
Cheers
